#!/bin/bash -e
SUCCESS="SUCCESS"
if [[ -f "`(pwd)`/.TEST" && ${SUCCESS} == "$(cat `(pwd)`/.TEST)" ]]; then
    status="success"
else
    status="failure"
fi
rm -rf `(pwd)`/.TEST

if [[ -n ${FLOW_ORG} ]]; then

curl -X POST ${FLOW_URL}/aha-flow-app/hook \
    -H "Authorization: ${AHA_FLOW_TOKEN}" \
    -H "content-type: application/json" \
    -d '{
    "org": "'${FLOW_ORG}'",
    "repo": "'${FLOW_REPO}'",
    "head_sha": "'${FLOW_HEAD_SHA}'",
    "status": "'completed'",
    "conclusion": "'${status}'",
    "id": "'${FLOW_ID}'"
    }'
fi
